### ISSUE TITLE
Fixed unit for gutters?

### ISSUE THREAD

**Issue by igorlanko** [PavelLaptev/tiny-flexbox-grid-system#1]
Hi Pavel,

Thanks a lot for the grid! One of the most straightforward to understand out there.

I'm curious, using the system you have, how would you approach fixed units for gutters? Say if I need fixed pixel gap between the columns and it only be adaptive, but not fluid as you have them in percentage.

And then just manually change them according to the viewport width. Same with margins.

Cheers!

**Comment by PavelLaptev** [comment]
Hi, @igorlanko 

Thank you for the question. Yes, I created this grid as a fully flexible grid because when you shrink the browser window the transition between gap sizes will be smoother. But sure you can make gaps fixed. So, here are our variables for gaps with percentage approach:

```scss
$desk-gutter: (
  (
      $grid-desktop-gutter /
        ($grid-desktop-breakpoint - ($grid-desktop-sideMargin * 2))
    ) * 100%
);
$tab-gutter: (
  (
      $grid-tablet-gutter /
        ($grid-tablet-breakpoint - ($grid-tablet-sideMargin * 2))
    ) * 100%
);
$mob-gutter: (
  (
      $grid-mobile-gutter /
        ($grid-mobile-breakpoint - ($grid-mobile-sideMargin * 2))
    ) * 100%
);
```

To turn percentage gaps into fixed, just replace all math operation with fixed gap variables like this:

```scss
$desk-gutter: $grid-desktop-gutter;
$tab-gutter: $grid-tablet-gutter;
$mob-gutter: $grid-mobile-gutter;
```

The same approach you can use for other percentage variables. Ping me if it helps 😄

**Comment by igorlanko** [comment]
@PavelLaptev, it helped! Makes perfect sense.

I also end up compensating padding values from the grid container width to make it pixel perfect.

Something like this:
```
 @media screen and (max-width: $grid-tablet-breakpoint) {
    width: calc(#{$tab-grid-width} + #{$grid-tablet-gutter};
  }
```

So at 1280 it works perfectly as designed:
<img width="599" alt="Screen Shot 2020-05-31 at 13 57 19" src="https://user-images.githubusercontent.com/31314207/83362503-b486e900-a346-11ea-9695-ef80d70ef384.png">
<img width="1157" alt="Screen Shot 2020-05-31 at 13 56 46" src="https://user-images.githubusercontent.com/31314207/83362505-b81a7000-a346-11ea-8f53-189f8c0f2bef.png">

Thanks a lot!

**Comment by PavelLaptev** [comment]
@igorlanko looks nice 👍
